version: '3.3'
services:
  web:
    build: .
    environment:
      - FLASK_ENV=dev
      - MONGODB_HOST=mongo-db
      - MONGODB_DB=red_development
    ports:
      - "5000:5000"
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
