"""empty message

Revision ID: b4d23623f20d
Revises: 4ae62fb59923
Create Date: 2017-11-05 00:24:31.485699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d23623f20d'
down_revision = '4ae62fb59923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    counties_table = op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(
        counties_table,
        [
            {'id':1, 'county':'Kent'},
            {'id':2, 'county':'Muskegon'},
            {'id':3, 'county':'Ottawa'},
            {'id':4, 'county':'Lake/Mason/Oceana'},
            {'id':5, 'county':'Allegan'}
        ]
    )

    overdose_preventions_table = op.create_table('overdose_preventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(
        overdose_preventions_table,
        [
            {'id':1, 'method':'Quality'},
            {'id':2, 'method':'Mixing'},
            {'id':3, 'method':'Using Alone'},
            {'id':4, 'method':'Tolerance/Period of Abstinence'},
            {'id':5, 'method':'Fentanyl'},
            {'id':6, 'method':'General Health'},
            {'id':7, 'method':'Depressed Breathing'},
            {'id':8, 'method':'Safer Use Methods'}
        ]
    )

    overdose_response_table = op.create_table('overdose_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(
        overdose_response_table,
        [
            {'id':1, 'response':'Signs of Overdose', 'category':'Assess'},
            {'id':2, 'response':'Stimulation', 'category':'Assess'},
            {'id':3, 'response':'Unresponsive + Opioid Use = Overdose', 'category':'Assess'},
            {'id':4, 'response':'Calling 911', 'category':'Administer'},
            {'id':5, 'response':'IM Naloxone (1-2mL thigh/shoulder/butt)', 'category':'Administer'},
            {'id':6, 'response':'IN Naloxone', 'category':'Administer'},
            {'id':7, 'response':'Rescue Breathing', 'category':'Aftercare'},
            {'id':8, 'response':'2nd dose of Naloxone', 'category':'Aftercare'},
            {'id':9, 'response':'Overdose Recurrence', 'category':'Aftercare'},
            {'id':10, 'response':'Storage', 'category':'Aftercare'},
            {'id':11, 'response':'Recovery Position', 'category':'Aftercare'},
        ]
    )

    op.create_table('orders_to_dispense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('know_someone_at_risk', sa.Boolean(), nullable=True),
    sa.Column('other_drug', sa.String(), nullable=True),
    sa.Column('use_substances_twice_per_month', sa.Boolean(), nullable=True),
    sa.Column('recent_abstinence_period', sa.Boolean(), nullable=True),
    sa.Column('when_recent_abstinence', sa.Text(), nullable=True),
    sa.Column('why_recent_abstinence', sa.Text(), nullable=True),
    sa.Column('num_overdoses', sa.Integer(), nullable=True),
    sa.Column('when_last_overdose', sa.Text(), nullable=True),
    sa.Column('what_drug_last_overdose', sa.Text(), nullable=True),
    sa.Column('num_overdoses_witnessed', sa.Integer(), nullable=True),
    sa.Column('num_overdoses_witnessed_hospital', sa.Integer(), nullable=True),
    sa.Column('num_overdoses_witnessed_died', sa.Integer(), nullable=True),
    sa.Column('naloxone_lot_num', sa.String(), nullable=True),
    sa.Column('naloxone_expiration_date', sa.Date(), nullable=True),
    sa.Column('num_naloxone_dispensed', sa.Integer(), nullable=True),
    sa.Column('narcan_lot_num', sa.String(), nullable=True),
    sa.Column('narcan_expiration_date', sa.Date(), nullable=True),
    sa.Column('num_narcan_dispensed', sa.Integer(), nullable=True),
    sa.Column('prescriber', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('other_location', sa.String(), nullable=True),
    sa.Column('employee_initials', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_to_dispense_drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orders_to_dispense_id', sa.Integer(), nullable=False),
    sa.Column('drugs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drugs_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['orders_to_dispense_id'], ['orders_to_dispense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_to_dispense_overdose_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orders_to_dispense_id', sa.Integer(), nullable=False),
    sa.Column('overdose_response_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orders_to_dispense_id'], ['orders_to_dispense.id'], ),
    sa.ForeignKeyConstraint(['overdose_response_id'], ['overdose_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_to_dispense_preventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orders_to_dispense_id', sa.Integer(), nullable=False),
    sa.Column('prevention_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orders_to_dispense_id'], ['orders_to_dispense.id'], ),
    sa.ForeignKeyConstraint(['prevention_id'], ['overdose_preventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('overdose_reversals', sa.Column('administered_route', sa.String(), nullable=True))
    op.add_column('overdose_reversals', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('overdose_reversals', sa.Column('other_drug', sa.String(), nullable=True))
    op.add_column('overdose_reversals', sa.Column('zip_code', sa.String(), nullable=True))
    op.drop_column('overdose_reversals', 'route')
    op.add_column('syringe_access', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('syringe_access', sa.Column('employee_initials', sa.String(), nullable=True))
    op.add_column('syringe_access', sa.Column('general_notes', sa.Text(), nullable=True))
    op.add_column('syringe_access', sa.Column('hcv_test', sa.Boolean(), nullable=True))
    op.add_column('syringe_access', sa.Column('hiv_test', sa.Boolean(), nullable=True))
    op.add_column('syringe_access', sa.Column('other_location', sa.String(), nullable=True))
    op.add_column('syringe_access', sa.Column('referral_notes', sa.Text(), nullable=True))
    op.drop_column('syringe_access', 'new_client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syringe_access', sa.Column('new_client', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('syringe_access', 'referral_notes')
    op.drop_column('syringe_access', 'other_location')
    op.drop_column('syringe_access', 'hiv_test')
    op.drop_column('syringe_access', 'hcv_test')
    op.drop_column('syringe_access', 'general_notes')
    op.drop_column('syringe_access', 'employee_initials')
    op.drop_column('syringe_access', 'date')
    op.add_column('overdose_reversals', sa.Column('route', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('overdose_reversals', 'zip_code')
    op.drop_column('overdose_reversals', 'other_drug')
    op.drop_column('overdose_reversals', 'notes')
    op.drop_column('overdose_reversals', 'administered_route')
    op.drop_table('orders_to_dispense_preventions')
    op.drop_table('orders_to_dispense_overdose_responses')
    op.drop_table('orders_to_dispense_drugs')
    op.drop_table('orders_to_dispense')
    op.drop_table('overdose_responses')
    op.drop_table('overdose_preventions')
    op.drop_table('counties')
    # ### end Alembic commands ###
