"""empty message

Revision ID: b1e9c7ed67d6
Revises: b4d23623f20d
Create Date: 2017-11-05 08:38:51.786851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e9c7ed67d6'
down_revision = 'b4d23623f20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syringe_access', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'syringe_access', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'syringe_access', type_='foreignkey')
    op.drop_column('syringe_access', 'location_id')
    # ### end Alembic commands ###
